# @package agent

# common
_target_: agent.diayn.DIAYNAgent
name: diayn
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
action_range: ??? # to be specified later
maze_type: ${maze_type}
device: ${device}
dtype: ${dtype}

update_every_steps: 2
num_expl_steps: ??? # to be specified later
hidden_dim: 128
feature_dim: 128
nstep: 1
batch_size: 64
use_tb: ${use_tb}
use_wandb: ${use_wandb}

# diayn
diayn_lr: 3e-4
diayn_scale: 1.0
update_skill_every_step: 25
skill_dim: 20
max_skill_dim: 200

# critic (SAC)
critic_target_tau: 0.005
critic_lr : 3e-4
critic_target_update_frequency: 2

# actor, alpha (SAC)
actor_update_frequency: 2
actor_lr : 3e-4
alpha_lr : 3e-4
log_std_bounds: [-5, 2]  # Actor의 log_std를 제한
init_alpha: 0.1

# fine-tuning
init_critic: true

# encoder
encoder_lr: 3e-4
update_encoder: ${update_encoder}
